version: '3.5'
services:
  angular:
    build: .
    volumes:
      - './app:/usr/src/app'
    ports:
      - '4200:4200'
      - '49153:49153'
    command: bash -c "npm install && ng serve --host 0.0.0.0 --port 4200 --poll 500"